require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - bin/*
    - tmp/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/ExampleLength:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false
