require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - bin/*
    - tmp/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Metrics/LineLength:
  Max: 120
